kind: pipeline
name: build
type: kubernetes

steps:
- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - env
  
- name: mark
  image: akhenakh/drone-deployment-mark:1.0
  settings:
  	webhook: https://xxx.api/
	target: prd
  when:
    status: [ success, failure ]
