kind: pipeline
name: build
type: kubernetes

steps:
- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - env

- name: docker-docker
  image: plugins/gcr
  settings:
    mirror: http://www.google.com
    config:
      from_secret: secret_config_pull
    dry_run: true
