kind: pipeline
name: build
type: kubernetes

steps:
- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - env
  
- name: mark
  image: akhenakh/drone-deployment-mark:latest
  settings:
    target: prd
    webhook: http://inair.space
  when:
    status: [ success, failure ]
