kind: pipeline
name: build
type: kubernetes

steps:
- name: pr
  image: drone/git
  commands:
  - git status
  
- name: test
  image: alpine:3.8
  commands:
  - echo hello
  - exit 2
  
- name: failenv
  image: alpine:3.8
  commands:
  - env
  when:
    status: [ success, failure ]
  depends_on:
    - test
    
- name: mark
  image: akhenakh/drone-deployment-mark:latest
  settings:
    target: prd
    webhook: http://inair.space
  when:
    status: [ success, failure ]
  depends_on:
    - test
---
kind: pipeline
name: test
type: kubernetes

steps:
- name: test2
  image: alpine:3.8
  commands:
  - echo hello 2
  - env
  
- name: test3
  image: alpine:3.8
  commands:
  - echo hello 3
  - env
  
- name: mark3
  image: akhenakh/drone-deployment-mark:latest
  settings:
    target: prd
    webhook: http://inair.space
  when:
    status: [ success, failure ]
